//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerPulse.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=141.98.157.118\\SQLEXPRESS;Initial Catalog=PowerPulse;Persist Security" +
            " Info=True;User ID=sa;Password=TesteBD;Encrypt=False")]
        public string PowerPulseConnectionString2 {
            get {
                return ((string)(this["PowerPulseConnectionString2"]));
=========
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=141.98.157.118\\1433 ;Initial Catalog=PowerPulse;Persist Security Info" +
            "=True;User ID=sa;Password=TesteBD;Encrypt=False")]
        public string Powerpulse {
            get {
                return ((string)(this["Powerpulse"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.0")]
        public string version {
            get {
                return ((string)(this["version"]));
            }
            set {
                this["version"] = value;
>>>>>>>>> Temporary merge branch 2
            }
        }
    }
}
